builds:
  - skip: true

source:
  enabled: true

sboms:
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

kos:
  - repository: ghcr.io/terotuomala/k8s-image-watcher
    base_image: cgr.dev/chainguard/static
    tags:
    - '{{.Tag}}'
    - latest
    bare: true
    preserve_import_paths: false
    platforms:
    - linux/amd64
    - linux/arm64

docker_signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    args:
    - 'sign'
    - '${artifact}'
    - "--yes" # needed on cosign 2.0.0+
    artifacts: manifests

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
