version: '3'

vars:
  ARTIFACT_FILE: "artifacts.json" 
  
tasks:
  dependencies:
    desc: Install dependencies
    cmds:
      - go mod tid

  dev:
    desc: Run the application in dev mode using skaffold
    cmds:
      - skaffold dev --profile dev --cleanup=false --status-check=false
  
  deploy:
    desc: Deploy the application using skaffold
    deps:
      - build
    cmds:
      - skaffold deploy --status-check=true

  generate-manifests:
    desc: Generate helm template using values.yaml
    cmds:
      - helm template k8s-image-watcher ./charts > k8s-image-watcher-template.yaml