version: '3'

vars:
  CLUSTER_NAME: k3s-local
  
tasks:
  tools:
    desc: Install tools for local development (k3d, skaffold)
    cmds:
      - brew install k3d skaffold

  deps:
    desc: Install go dependencies
    cmds:
      - go mod tidy

  dev:
    desc: Run the application in dev mode using skaffold
    cmds:
      - skaffold dev --profile dev --cleanup=false --status-check=false
  
  deploy:
    desc: Deploy the application using skaffold
    cmds:
      - skaffold deploy --status-check=true

  generate-manifests:
    desc: Generate helm template using values.yaml
    cmds:
      - helm template k8s-image-watcher ./charts/k8s-image-watcher > k8s-image-watcher-manifests.yaml

  create-k3s-cluster:
    desc: Create a local k3s cluster
    preconditions:
      - sh: command -v k3d
        msg: K3d is required but it's not installed. Aborting.
    cmds:
      - >-
        k3d cluster create "{{.CLUSTER_NAME}}"
        --servers 1
        --agents {{.CLI_ARGS | default "0"}}
        --k3s-arg '--disable=traefik@server:0'
        --no-lb
        --wait
  
  delete-k3s-cluster:
    desc: Delete the local k3s cluster
    cmds:
      - k3d cluster delete "{{.CLUSTER_NAME}}"