apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-image-watcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-image-watcher.labels" . | nindent 4 }}

