{{- if ne .Values.watch.namespace "" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-image-watcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-image-watcher.labels" . | nindent 4 }}
  annotations:
    {{- toYaml . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-image-watcher.fullname" . }}
subjects:
- kind: ServiceAccount
  name:  {{- include "k8s-image-watcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}