# Default values for k8s-image-watcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/terotuomala/k8s-image-watcher
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podAnnotations: {}

securityContext: {}

resources:
  limits:
    cpu: 5m
    memory: 15Mi
  requests:
    cpu: 1m
    memory: 5Mi

nodeSelector: {}

tolerations: []

affinity: {}

commonLabels: {}

serviceAccount:
  create: true

logging:
  level: info

watch:
  namespace: ""
  deployment: true
  daemonset: false
  statefulset: true

slack:
  enabled: false
  channel: ""
  messageTitle: ""
