---
name: GoReleaser

on:
  push:
    tags:
      - '*'

permissions:
   contents: write # needed to write releases
   id-token: write # needed for keyless signing

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install cosign  
        uses: sigstore/cosign-installer@v3.1.1

      - name: Install syft
        uses: anchore/sbom-action/download-syft@v0.14.3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}